### ISSUE TITLE
support github ticket IDs

### ISSUE THREAD

**Issue by jlevon** [joyent/prr#10]
Currently prr only supports JIRA ticket titles - it should also allow joyent/prr#7 format

**Comment by timfoster** [comment]
What formats are we expecting here?  Which of these do we want:

```
TICKET-1337 this is a Jira synopsis
12345 that was an Illumos id and this is the synopsis
joyent/foo#678 that was a GitHub id, this is the synopsis
this is a synopsis, confusingly the ticket number at the end #910
this is the title of PR123 with no obv relation to the ticket number immediately below (#123)
Fixes #456
```

I'd imagine we'd like all of the first three ticket numbers extracted, but that the other two ticket numbers would be tricky.

**Comment by jlevon** [comment]
I don't think we need to support redmine tickets.
The other two, yes - I think that's what grr supported.
The others: not necessary I'd say.

**Comment by timfoster** [comment]
Thanks, that seems reasonable. I'll roll this into joyent/prr#20
